room:
  - name: "test"
    chat:
      - type: "slack"
        chatID:
          - ""
      - type: "discord"
        chatID:
          - ""
      - type: "telegram"
        chatID:
          - ""
      - type: "matrix"
        chatID:
          - ""

slack:
  token:
  appLevelToken:

discord:
  token:

telegram:
  token:
matrix:
  host: https://matrix.org
  user: ""
  password: ""

emoji: # emoji type order. slack,emoji
  - "+1,ğŸ‘"
  - "clap,ğŸ‘"
  - "ok_hand,ğŸ‘Œ"
  - "white_check_mark,âœ…"
  - "eyes,ğŸ‘€"
  - "smile,ğŸ˜„"

